// packages/ui/src/solid-components/CodeViewer.tsx
import { highlightCode, readFile } from '@openterminal-ui/core';
import { createEffect, createSignal } from 'solid-js';

export interface CodeViewerProps {
  filePath: string | null;
  isActive: boolean;
}

export function CodeViewer(props: CodeViewerProps) {
  const [content, setContent] = createSignal<string>('');

  createEffect(() => {
    const fp = props.filePath;
    if (fp) {
      try {
        const raw = readFile(fp);
        const ext = fp.split('.').pop() || 'txt';
        const highlighted = highlightCode(raw, ext);
        setContent(highlighted);
      } catch {
        setContent(`Error reading file: ${fp}`);
      }
    } else {
      setContent('No file selected.');
    }
  });

  return (
    <box
      style={{
        flexDirection: 'column',
        borderStyle: props.isActive ? 'double' : 'single',
        borderColor: props.isActive ? 'blue' : 'gray',
        padding: 1,
        flexGrow: 1,
      }}
    >
      <text style={{ bold: true, color: 'yellow' }}>{props.filePath || 'Code Viewer'}</text>
      <box style={{ overflow: 'hidden' }}>
        <text>{content()}</text>
      </box>
    </box>
  );
}

// packages/ui/src/components/CodeViewer.tsx
import React, { useEffect, useState } from 'react';
import { Box, Text } from 'ink';
import { readFile, highlightCode } from '@openterminal-ui/core';

export interface CodeViewerProps {
  filePath: string | null;
  isActive: boolean;
}

export const CodeViewer: React.FC<CodeViewerProps> = ({ filePath, isActive }) => {
  const [content, setContent] = useState<string>('');

  useEffect(() => {
    if (filePath) {
      try {
        const raw = readFile(filePath);
        // Apply syntax highlighting via Rust
        // Determine extension
        const ext = filePath.split('.').pop() || 'txt';
        const highlighted = highlightCode(raw, ext);
        setContent(highlighted);
      } catch (e) {
        setContent(`Error reading file: ${filePath}`);
      }
    } else {
        setContent("No file selected.");
    }
  }, [filePath]);

  return (
    <Box flexDirection="column" borderStyle={isActive ? "double" : "single"} borderColor={isActive ? "blue" : "gray"} padding={1} flexGrow={1}>
      <Text bold color="yellow">{filePath || "Code Viewer"}</Text>
      {/* Ink Text handles basic ANSI, but we might need to be careful with large files */}
      <Box overflowY="hidden">
          <Text>{content}</Text>
      </Box>
    </Box>
  );
};
